/*
  create_driver_survey_table.sql
  Creates 6 Driver Survey tables in the Cab schema with proper column types.
  Uses IF NOT EXISTS to avoid dropping existing tables.

  Column types derived from:
    - Sources/column_rename_mapping.json  (dtype field)
    - Computed/derived columns detected from CSV data

  Tables:
    - Cab.DriverSurvey_ShortMain  (68 columns)
    - Cab.DriverSurvey_ShortRare  (176 columns)
    - Cab.DriverSurvey_WideMain  (67 columns)
    - Cab.DriverSurvey_WideRare  (190 columns)
    - Cab.DriverSurvey_LongMain  (28 columns)
    - Cab.DriverSurvey_LongRare  (9 columns)

  Usage: Execute this entire script in SSMS.
         It will only create tables that do not already exist.
*/

-- ============================================================
-- Cab.DriverSurvey_ShortMain  (68 columns)
-- ============================================================
IF OBJECT_ID(N'Cab.DriverSurvey_ShortMain', N'U') IS NULL
BEGIN
    CREATE TABLE [Cab].[DriverSurvey_ShortMain] (
        [recordID] INT NOT NULL,
        [datetime] DATETIME NULL,
        [_source_file] NVARCHAR(500) NULL,
        [weeknumber] INT NULL,
        [snapp_age] NVARCHAR(500) NULL,
        [tapsi_age] NVARCHAR(500) NULL,
        [snapp_trip_count] NVARCHAR(500) NULL,
        [tapsi_trip_count] NVARCHAR(500) NULL,
        [snapp_fare_satisfaction] INT NULL,
        [snapp_req_count_satisfaction] INT NULL,
        [snapp_income_satisfaction] INT NULL,
        [tapsi_fare_satisfaction] INT NULL,
        [tapsi_req_count_satisfaction] INT NULL,
        [tapsi_income_satisfaction] INT NULL,
        [snapp_trip_count_commfree] NVARCHAR(500) NULL,
        [snapp_incentive_rial_details] NVARCHAR(500) NULL,
        [snapp_joining_bonus] NVARCHAR(500) NULL,
        [tapsi_gotmessage_text_incentive] NVARCHAR(500) NULL,
        [tapsi_inactive_b4_incentive] NVARCHAR(500) NULL,
        [tapsi_trip_count_commfree] NVARCHAR(500) NULL,
        [tapsi_incentive_rial_details] NVARCHAR(500) NULL,
        [tapsi_joining_bonus] NVARCHAR(500) NULL,
        [tapsi_magical_window] NVARCHAR(500) NULL,
        [tapsi_magical_window_income] NVARCHAR(500) NULL,
        [tapsi_navigation_type] NVARCHAR(500) NULL,
        [snapp_last_trip_navigation] NVARCHAR(500) NULL,
        [city] NVARCHAR(500) NULL,
        [tapsi_carpooling_familiar] NVARCHAR(500) NULL,
        [tapsi_carpooling_gotoffer_accepted] NVARCHAR(500) NULL,
        [tapsi_carpooling_satisfaction_overall] INT NULL,
        [gender] NVARCHAR(500) NULL,
        [age] NVARCHAR(500) NULL,
        [education] NVARCHAR(500) NULL,
        [marital_status] NVARCHAR(500) NULL,
        [original_job] NVARCHAR(500) NULL,
        [active_time] NVARCHAR(500) NULL,
        [snapp_gotmessage_text_incentive] NVARCHAR(500) NULL,
        [snapp_incentive_active_duration] NVARCHAR(500) NULL,
        [snapp_overall_incentive_satisfaction] INT NULL,
        [snapp_incentive_participation] NVARCHAR(500) NULL,
        [tapsi_incentive_active_duration] NVARCHAR(500) NULL,
        [tapsi_overall_incentive_satisfaction] INT NULL,
        [tapsi_incentive_participation] NVARCHAR(500) NULL,
        [snapp_incentive_message_participation] NVARCHAR(500) NULL,
        [snapp_overall_satisfaction_snapp] INT NULL,
        [snapp_trip_count_commfree_discount] NVARCHAR(500) NULL,
        [tapsi_trip_count_commfree_discount] NVARCHAR(500) NULL,
        [joint_by_signup] INT NULL,
        [active_joint] INT NULL,
        [snapp_ride] FLOAT NULL,
        [tapsi_ride] FLOAT NULL,
        [tapsi_commfree_disc_ride] FLOAT NULL,
        [snapp_commfree_disc_ride] FLOAT NULL,
        [snapp_diff_commfree] FLOAT NULL,
        [tapsi_diff_commfree] FLOAT NULL,
        [snapp_commfree] FLOAT NULL,
        [tapsi_commfree] FLOAT NULL,
        [snapp_incentive] FLOAT NULL,
        [tapsi_incentive] FLOAT NULL,
        [wheel] FLOAT NULL,
        [cooperation_type] NVARCHAR(500) NULL,
        [snapp_LOC] FLOAT NULL,
        [tapsi_LOC] FLOAT NULL,
        [age_group] NVARCHAR(500) NULL,
        [edu] FLOAT NULL,
        [marr_stat] FLOAT NULL,
        [snapp_incentive_category] NVARCHAR(500) NULL,
        [tapsi_incentive_category] NVARCHAR(500) NULL
    );
    PRINT 'Created Cab.DriverSurvey_ShortMain';
END
ELSE
    PRINT 'Cab.DriverSurvey_ShortMain already exists -- skipped.';
GO

-- ============================================================
-- Cab.DriverSurvey_ShortRare  (176 columns)
-- ============================================================
IF OBJECT_ID(N'Cab.DriverSurvey_ShortRare', N'U') IS NULL
BEGIN
    CREATE TABLE [Cab].[DriverSurvey_ShortRare] (
        [recordID] INT NOT NULL,
        [datetime] DATETIME NULL,
        [_source_file] NVARCHAR(500) NULL,
        [weeknumber] INT NULL,
        [snapp_gotmessage_incentive] NVARCHAR(500) NULL,
        [snapp_incentive_type] NVARCHAR(500) NULL,
        [snapp_incentive_length] NVARCHAR(500) NULL,
        [snapp_incentive_satisfaction] INT NULL,
        [snapp_last_incentive_participation] NVARCHAR(500) NULL,
        [tapsi_incentive_length] NVARCHAR(500) NULL,
        [tapsi_incentive_satisfaction] INT NULL,
        [tapsi_last_incentive_participation] NVARCHAR(500) NULL,
        [tapsi_magicwindow_familiar] NVARCHAR(500) NULL,
        [snapp_collab_reason] NVARCHAR(500) NULL,
        [tapsi_collab_reason] NVARCHAR(500) NULL,
        [gotmessage_satisfaction_sms] INT NULL,
        [gotmessage_satisfaction_call] INT NULL,
        [gotmessage_satisfaction_app] INT NULL,
        [gotmessage_satisfaction_telegram] INT NULL,
        [gotmessage_satisfaction_instagram] INT NULL,
        [driverapp_off_familiar] NVARCHAR(500) NULL,
        [driverapp_campagin_familiar] NVARCHAR(500) NULL,
        [driverapp_feature_use] NVARCHAR(500) NULL,
        [driverapp_feature_satisfaction] INT NULL,
        [intercitysnapp_familiar] NVARCHAR(500) NULL,
        [snapp_ecoplus_familiar] NVARCHAR(500) NULL,
        [intercitytapsi_familiar] NVARCHAR(500) NULL,
        [snapp_distancetooring_time_satisfaction] INT NULL,
        [tapsi_distancetooring_time_satisfaction] INT NULL,
        [carpooling_15%] NVARCHAR(500) NULL,
        [snapp_overall_satisfaction] INT NULL,
        [tapsi_overall_satisfaction] INT NULL,
        [snapp_register_type] NVARCHAR(500) NULL,
        [snapp_registration_motivation] NVARCHAR(500) NULL,
        [tapsi_register_type] NVARCHAR(500) NULL,
        [tapsi_registration_motivation] NVARCHAR(500) NULL,
        [tapsi_invite_to_reg] NVARCHAR(500) NULL,
        [tapsi_invite_to_reg_bonus] NVARCHAR(500) NULL,
        [snapp_recommend] INT NULL,
        [tapsidriver_tapsi_recommend] INT NULL,
        [snapp_ecoplus_access_usage] NVARCHAR(500) NULL,
        [snapp_ecoplus_accepted] NVARCHAR(500) NULL,
        [snapp_ecoplus_tripcount] NVARCHAR(500) NULL,
        [tapsi_plus_tripcount] NVARCHAR(500) NULL,
        [ratepassenger_familiar_use] NVARCHAR(500) NULL,
        [tapsi_carpooling_satisfaction] INT NULL,
        [snapp_CS_satisfaction_overall] INT NULL,
        [snapp_CS_satisfaction_waittime] INT NULL,
        [snapp_CS_satisfaction_solution] INT NULL,
        [snapp_CS_satisfaction_behaviour] INT NULL,
        [snapp_CS_satisfaction_relevance] INT NULL,
        [snapp_CS_satisfaction_important_reason] NVARCHAR(500) NULL,
        [snapp_unsatisfaction_app_support] NVARCHAR(500) NULL,
        [snapp_CS_solved] NVARCHAR(500) NULL,
        [tapsi_CS_] NVARCHAR(500) NULL,
        [tapsi_CS_satisfaction_overall] INT NULL,
        [tapsi_CS_satisfaction_waittime] INT NULL,
        [tapsi_CS_satisfaction_solution] INT NULL,
        [tapsi_CS_satisfaction_behaviour] INT NULL,
        [tapsi_CS_satisfaction_relevance] INT NULL,
        [tapsi_CS_satisfaction_important_reason] NVARCHAR(500) NULL,
        [tapsi_unsatisfaction_app_support] NVARCHAR(500) NULL,
        [tapsi_CS_solved] NVARCHAR(500) NULL,
        [snapp_refer_others] INT NULL,
        [tapsi_refer_others] INT NULL,
        [snappcarfix_familiar] NVARCHAR(500) NULL,
        [snappcarfix_use_ever] NVARCHAR(500) NULL,
        [snappcarfix_satisfaction_experience] INT NULL,
        [snappcarfix_satisfaction_productprice] INT NULL,
        [snappcarfix_satisfaction_quality] INT NULL,
        [snappcarfix_satisfaction_variety] INT NULL,
        [snappcarfix_satisfaction_buyingprocess] INT NULL,
        [snappcarfix_satisfaction_deliverytime] INT NULL,
        [snappcarfix_satisfaction_waittime] INT NULL,
        [snappcarfix_satisfaction_behaviour] INT NULL,
        [snappcarfix_recommend] INT NULL,
        [tapsigarage_familiar] NVARCHAR(500) NULL,
        [tapsigarage_use_ever] NVARCHAR(500) NULL,
        [tapsigarage_satisfaction_experience] INT NULL,
        [tapsigarage_satisfaction_productprice] INT NULL,
        [tapsigarage_satisfaction_quality_experience] INT NULL,
        [tapsigarage_satisfaction_variety_experience] INT NULL,
        [tapsigarage_satisfaction_buyingprocess] INT NULL,
        [tapsigarage_satisfaction_deliverytime] INT NULL,
        [tapsigarage_satisfaction_waittime] INT NULL,
        [tapsigarage_satisfaction_behaviour] INT NULL,
        [tapsigarage_recommend] INT NULL,
        [snapp_navigation_app_satisfaction] INT NULL,
        [recommendation_googlemap] INT NULL,
        [recommendation_waze] INT NULL,
        [recommendation_neshan] INT NULL,
        [recommendation_balad] INT NULL,
        [recommendation_googlemap_last3month] NVARCHAR(500) NULL,
        [recommendation_waze_last3month] NVARCHAR(500) NULL,
        [recommendation_neshan_last3month] NVARCHAR(500) NULL,
        [recommendation_balad_last3month] NVARCHAR(500) NULL,
        [tapsi_in_app_navigation_usage] NVARCHAR(500) NULL,
        [tapsi_in_app_navigation_satisfaction] INT NULL,
        [carservice_familiar_snapp] NVARCHAR(500) NULL,
        [carservice_familiar_tapsi] NVARCHAR(500) NULL,
        [nowrouz_leage_awareness] NVARCHAR(500) NULL,
        [carservice_familiar_maxim] NVARCHAR(500) NULL,
        [tapsi_overall_satisfaction_snapp] INT NULL,
        [snapp_main_reg_reason] NVARCHAR(500) NULL,
        [tapsi_main_reg_reason] NVARCHAR(500) NULL,
        [snappdriver_tapsi_recommend] INT NULL,
        [snapp_CS] NVARCHAR(500) NULL,
        [unpaid_by_passenger] NVARCHAR(500) NULL,
        [carservice_familiar_snappcarfix] NVARCHAR(500) NULL,
        [carservice_familiar_tapsigarage] NVARCHAR(500) NULL,
        [snappcarfix_use_lastmo] NVARCHAR(500) NULL,
        [snappcarfix_satisfaction_overall] INT NULL,
        [snappcarfix_satisfaction_quality_lastm] INT NULL,
        [snappcarfix_satisfaction_price_lastm] INT NULL,
        [snappcarfix_satisfaction_variety_lastm] INT NULL,
        [snappcarfix_satisfaction_easyusage] INT NULL,
        [snappcarfix_satisfaction_ontimedelivery] INT NULL,
        [snappcarfix_satisfaction_CS] INT NULL,
        [tapsigarage_use_lastmo] NVARCHAR(500) NULL,
        [tapsigarage_satisfaction_overall] INT NULL,
        [tapsigarage_satisfaction_quality] INT NULL,
        [tapsigarage_satisfaction_price] INT NULL,
        [tapsigarage_satisfaction_variety] INT NULL,
        [tapsigarage_satisfaction_easyusage] INT NULL,
        [tapsigarage_satisfaction_ontimedelivery] INT NULL,
        [tapsigarage_satisfaction_CS] INT NULL,
        [tapsi_carpooling_count] NVARCHAR(500) NULL,
        [incentive_rules] NVARCHAR(500) NULL,
        [snapp_use_nextweek] NVARCHAR(500) NULL,
        [snapp_speed_satisfaction] INT NULL,
        [tapsi_speed_satisfaction] INT NULL,
        [mixincentive] NVARCHAR(500) NULL,
        [mixincentive_activate_familiar] NVARCHAR(500) NULL,
        [mixincentive_tripeffect] NVARCHAR(500) NULL,
        [mixincentive_onlysnapp] NVARCHAR(500) NULL,
        [mixincentive_choice] NVARCHAR(500) NULL,
        [incentive_preference] NVARCHAR(500) NULL,
        [gps_problem] NVARCHAR(500) NULL,
        [gps_interrupt_impact] NVARCHAR(500) NULL,
        [fixlocation_familiar] NVARCHAR(500) NULL,
        [fixlocation_use] NVARCHAR(500) NULL,
        [fixlocation_satisfaction] INT NULL,
        [tapsi_gps_better] NVARCHAR(500) NULL,
        [OS] NVARCHAR(500) NULL,
        [snapp_gps_stage] NVARCHAR(500) NULL,
        [tapsi_gps_stage] NVARCHAR(500) NULL,
        [tapsi_offline_navigation_familiar] NVARCHAR(500) NULL,
        [tapsi_offline_navigation_usage] NVARCHAR(500) NULL,
        [better_offline_navigation] NVARCHAR(500) NULL,
        [tapsi_overall_satisfaction_tapsi] INT NULL,
        [snapp_participate_feeling] NVARCHAR(500) NULL,
        [snapp_not_talking_reason] NVARCHAR(500) NULL,
        [snapp_comm_info] NVARCHAR(500) NULL,
        [snapp_tax_info] NVARCHAR(500) NULL,
        [tapsi_comm_info] NVARCHAR(500) NULL,
        [tapsi_tax_info] NVARCHAR(500) NULL,
        [snapp_accepted_trip_length] NVARCHAR(500) NULL,
        [tapsi_accepted_trip_length] NVARCHAR(500) NULL,
        [snapp_unpaid_by_passenger_followup] NVARCHAR(500) NULL,
        [snapp_unpaid_by_passenger_count] NVARCHAR(500) NULL,
        [snapp_compensate_unpaid_by_passenger] NVARCHAR(500) NULL,
        [snapp_satisfaction_followup_overall] INT NULL,
        [snapp_satisfaction_followup_time] INT NULL,
        [tapsi_unpaid_by_passenger_followup] NVARCHAR(500) NULL,
        [tapsi_unpaid_by_passenger_count] NVARCHAR(500) NULL,
        [tapsi_compensate_unpaid_by_passenger] NVARCHAR(500) NULL,
        [tapsi_satisfaction_followup_overall] INT NULL,
        [tapsi_satisfaction_followup_time] INT NULL,
        [snapp_better_income] NVARCHAR(500) NULL,
        [tapsi_better_income] NVARCHAR(500) NULL,
        [snapp_familiarity_accepted_trip%] NVARCHAR(500) NULL,
        [max_demand] NVARCHAR(500) NULL,
        [demand_process] NVARCHAR(500) NULL,
        [missed_demand_per_10] NVARCHAR(500) NULL,
        [snapp_incentive_category] NVARCHAR(500) NULL,
        [tapsi_incentive_category] NVARCHAR(500) NULL
    );
    PRINT 'Created Cab.DriverSurvey_ShortRare';
END
ELSE
    PRINT 'Cab.DriverSurvey_ShortRare already exists -- skipped.';
GO

-- ============================================================
-- Cab.DriverSurvey_WideMain  (67 columns)
-- ============================================================
IF OBJECT_ID(N'Cab.DriverSurvey_WideMain', N'U') IS NULL
BEGIN
    CREATE TABLE [Cab].[DriverSurvey_WideMain] (
        [recordID] INT NOT NULL,
        [datetime] DATETIME NULL,
        [_source_file] NVARCHAR(500) NULL,
        [weeknumber] INT NULL,
        [Snapp Last Incentive Unsatisfaction__Not Available] INT NULL,
        [Snapp Last Incentive Unsatisfaction__Improper Amount] INT NULL,
        [Snapp Last Incentive Unsatisfaction__No Time todo] INT NULL,
        [Snapp Last Incentive Unsatisfaction__difficult] INT NULL,
        [Snapp Last Incentive Unsatisfaction__Non Payment] INT NULL,
        [Snapp Incentive GotBonus__Rial] INT NULL,
        [Snapp Incentive GotBonus__Nothing] INT NULL,
        [Snapp Incentive GotBonus__Commission-free/Discount] INT NULL,
        [Snapp Incentive Type__Commission Free on some trips] INT NULL,
        [Snapp Incentive Type__Pay After Ride] INT NULL,
        [Snapp Incentive Type__Ride-Based Commission-free] INT NULL,
        [Snapp Incentive Type__Earning-based Commission-free] INT NULL,
        [Snapp Incentive Type__Income Guarantee] INT NULL,
        [Snapp Incentive Type__Pay After Income] INT NULL,
        [Tapsi Last Incentive Unsatisfaction__I didn't have time to do it] INT NULL,
        [Tapsi Last Incentive Unsatisfaction__Improper Amount] INT NULL,
        [Tapsi Last Incentive Unsatisfaction__not enough time  to do] INT NULL,
        [Tapsi Last Incentive Unsatisfaction__Difficult to do] INT NULL,
        [Tapsi Last Incentive Unsatisfaction__Non Payment/delay] INT NULL,
        [Tapsi Incentive GotBonus__Rial] INT NULL,
        [Tapsi Incentive GotBonus__Nothing] INT NULL,
        [Tapsi Incentive GotBonus__Commission-free/Discount] INT NULL,
        [Tapsi Incentive Type__Commission Free on some trips] INT NULL,
        [Tapsi Incentive Type__Pay After Ride] INT NULL,
        [Tapsi Incentive Type__Ride-Based Commission-free] INT NULL,
        [Tapsi Incentive Type__Earning-based Commission-free] INT NULL,
        [Tapsi Incentive Type__Income Guarantee] INT NULL,
        [Tapsi Incentive Type__Pay After Income] INT NULL,
        [Tapsi Carpooling refusal__Canceled by Passenger] INT NULL,
        [Tapsi Carpooling refusal__Long Wait Time] INT NULL,
        [Tapsi Carpooling refusal__Passenger Distance] INT NULL,
        [Tapsi Carpooling refusal__Not Familiar] INT NULL,
        [Tapsi Incentive Unsatisfaction__Not Available] INT NULL,
        [Tapsi Incentive Unsatisfaction__Improper Amount] INT NULL,
        [Tapsi Incentive Unsatisfaction__No Time todo] INT NULL,
        [Tapsi Incentive Unsatisfaction__difficult] INT NULL,
        [Tapsi Incentive Unsatisfaction__Non Payment] INT NULL,
        [Snapp Incentive Unsatisfaction__No Available Time] INT NULL,
        [Snapp Incentive Unsatisfaction__Improper Amount] INT NULL,
        [Snapp Incentive Unsatisfaction__No Time todo] INT NULL,
        [Snapp Incentive Unsatisfaction__difficult] INT NULL,
        [Snapp Incentive Unsatisfaction__Non Payment] INT NULL,
        [joint_by_signup] INT NULL,
        [active_joint] INT NULL,
        [snapp_ride] FLOAT NULL,
        [tapsi_ride] FLOAT NULL,
        [tapsi_commfree_disc_ride] FLOAT NULL,
        [snapp_commfree_disc_ride] FLOAT NULL,
        [snapp_diff_commfree] FLOAT NULL,
        [tapsi_diff_commfree] FLOAT NULL,
        [snapp_commfree] FLOAT NULL,
        [tapsi_commfree] FLOAT NULL,
        [snapp_incentive] FLOAT NULL,
        [tapsi_incentive] FLOAT NULL,
        [wheel] FLOAT NULL,
        [cooperation_type] NVARCHAR(500) NULL,
        [snapp_LOC] FLOAT NULL,
        [tapsi_LOC] FLOAT NULL,
        [age_group] NVARCHAR(500) NULL,
        [edu] FLOAT NULL,
        [marr_stat] FLOAT NULL,
        [snapp_incentive_category] NVARCHAR(500) NULL,
        [tapsi_incentive_category] NVARCHAR(500) NULL
    );
    PRINT 'Created Cab.DriverSurvey_WideMain';
END
ELSE
    PRINT 'Cab.DriverSurvey_WideMain already exists -- skipped.';
GO

-- ============================================================
-- Cab.DriverSurvey_WideRare  (190 columns)
-- ============================================================
IF OBJECT_ID(N'Cab.DriverSurvey_WideRare', N'U') IS NULL
BEGIN
    CREATE TABLE [Cab].[DriverSurvey_WideRare] (
        [recordID] INT NOT NULL,
        [datetime] DATETIME NULL,
        [_source_file] NVARCHAR(500) NULL,
        [weeknumber] INT NULL,
        [Snapp Request Refusal__Application Problems] INT NULL,
        [Snapp Request Refusal__Low Fare] INT NULL,
        [Snapp Request Refusal__Short Accept Time] INT NULL,
        [Snapp Request Refusal__Not Realized There's Request] INT NULL,
        [Snapp Request Refusal__Unfamiliar Route] INT NULL,
        [Snapp Request Refusal__Wait for better Offer] INT NULL,
        [Snapp Request Refusal__Traffic] INT NULL,
        [Snapp Request Refusal__Unfamiliar App] INT NULL,
        [Snapp Request Refusal__Target Destination] INT NULL,
        [Snapp Request Refusal__Internet Problems] INT NULL,
        [Snapp Request Refusal__Long DistanceToOrigin] INT NULL,
        [Snapp Request Refusal__Long Route] INT NULL,
        [Snapp Request Refusal__Working with Tapsi] INT NULL,
        [Tapsi Request Refusal__Application Problems] INT NULL,
        [Tapsi Request Refusal__Low Fare] INT NULL,
        [Tapsi Request Refusal__Short Accept Time] INT NULL,
        [Tapsi Request Refusal__Not Realized There's Request] INT NULL,
        [Tapsi Request Refusal__Unfamiliar Route] INT NULL,
        [Tapsi Request Refusal__Wait for better Offer] INT NULL,
        [Tapsi Request Refusal__Traffic] INT NULL,
        [Tapsi Request Refusal__Unfamiliar App] INT NULL,
        [Tapsi Request Refusal__Target Destination] INT NULL,
        [Tapsi Request Refusal__Internet Problems] INT NULL,
        [Tapsi Request Refusal__Long DistanceToOrigin] INT NULL,
        [Tapsi Request Refusal__Long Route] INT NULL,
        [Tapsi Request Refusal__Working with Tapsi] INT NULL,
        [Snapp Got Message Type__Sms] INT NULL,
        [Snapp Got Message Type__Call] INT NULL,
        [Snapp Got Message Type__Snapp Drivers App] INT NULL,
        [Snapp Got Message Type__Snapp Instagram Page] INT NULL,
        [Snapp Got Message Type__Snapp Telegram Channel] INT NULL,
        [Snapp Got Message Type__Notification Bar] INT NULL,
        [Snapp Got Message Type__هیچکدام.] INT NULL,
        [Snapp Driversapp Broadcast Channel__Telegram] INT NULL,
        [Snapp Driversapp Broadcast Channel__Instagram (drivers.snapp@)] INT NULL,
        [Snapp Driversapp Broadcast Channel__SnappClub (club.snapp.ir)] INT NULL,
        [Snapp Driversapp Broadcast Channel__هیچ کدام] INT NULL,
        [Carpooling 15% Refusal__Passenger Cancelling] INT NULL,
        [Carpooling 15% Refusal__Long Wait Time] INT NULL,
        [Carpooling 15% Refusal__long distance Routes] INT NULL,
        [Carpooling 15% Refusal__Unfamiliar Service] INT NULL,
        [Snapp Ecoplus Refusal__Distance to origin was Long] INT NULL,
        [Snapp Ecoplus Refusal__Fare] INT NULL,
        [Snapp Ecoplus Refusal__High Commission] INT NULL,
        [Snapp Ecoplus Refusal__long Trip] INT NULL,
        [Snapp Ecoplus Refusal__Bad Destination] INT NULL,
        [Snapp Ecoplus Refusal__Out of Range Distance] INT NULL,
        [Snapp Customer Support Category__Fare] INT NULL,
        [Snapp Customer Support Category__Cancelling] INT NULL,
        [Snapp Customer Support Category__Location Change] INT NULL,
        [Snapp Customer Support Category__Trip Problems] INT NULL,
        [Snapp Customer Support Category__Incentive] INT NULL,
        [Snapp Customer Support Category__Petrol] INT NULL,
        [Snapp Customer Support Category__Drivers Club] INT NULL,
        [Snapp Customer Support Category__Settlement] INT NULL,
        [Snapp Customer Support Category__Mask Wearing] INT NULL,
        [Snapp Customer Support Category__Block] INT NULL,
        [Snapp Customer Support Category__Registration] INT NULL,
        [Snapp Customer Support Category__Technical] INT NULL,
        [Tapsi Customer Support Category__Fare] INT NULL,
        [Tapsi Customer Support Category__Cancelling] INT NULL,
        [Tapsi Customer Support Category__Loc Change] INT NULL,
        [Tapsi Customer Support Category__Trip Problems] INT NULL,
        [Tapsi Customer Support Category__Incentive] INT NULL,
        [Tapsi Customer Support Category__Petrol] INT NULL,
        [Tapsi Customer Support Category__Drivers Club] INT NULL,
        [Tapsi Customer Support Category__Settlement] INT NULL,
        [Tapsi Customer Support Category__Mask Wearing] INT NULL,
        [Tapsi Customer Support Category__Block] INT NULL,
        [Tapsi Customer Support Category__Registration] INT NULL,
        [Tapsi Customer Support Category__Technical] INT NULL,
        [Snappcarfix NotUse Reason__Confusing] INT NULL,
        [Snappcarfix NotUse Reason__Low Diversity] INT NULL,
        [Snappcarfix NotUse Reason__Technical Promblems] INT NULL,
        [Snappcarfix NotUse Reason__High Price] INT NULL,
        [Navigation Familiarity__Google Map] INT NULL,
        [Navigation Familiarity__Waze] INT NULL,
        [Navigation Familiarity__Neshan] INT NULL,
        [Navigation Familiarity__Balad] INT NULL,
        [Navigation Familiarity__هیچ کدام] INT NULL,
        [Navigation Installed__Google Map] INT NULL,
        [Navigation Installed__Waze] INT NULL,
        [Navigation Installed__Neshan] INT NULL,
        [Navigation Installed__Balad] INT NULL,
        [Navigation Installed__هیچ کدام] INT NULL,
        [Navigation Used__Google Map] INT NULL,
        [Navigation Used__Waze] INT NULL,
        [Navigation Used__Neshan] INT NULL,
        [Navigation Used__Balad] INT NULL,
        [Navigation Used__هیچ کدام] INT NULL,
        [Snapp Navigation Refusal__Used Driver App Map] INT NULL,
        [Snapp Navigation Refusal__Familiar Address] INT NULL,
        [Snapp Navigation Refusal__Asked Passenger] INT NULL,
        [Snapp Navigation Refusal__App Error] INT NULL,
        [Snapp Navigation Refusal__Difficult to switch] INT NULL,
        [Snapp Navigation Refusal__Distraction] INT NULL,
        [Snapp Navigation Refusal__Slow navigation] INT NULL,
        [Snapp Navigation Refusal__Wrong route] INT NULL,
        [Snapp Navigation Refusal__Wrong Location] INT NULL,
        [Snapp Navigation Refusal__Wrong info] INT NULL,
        [Snapp Navigation Refusal__Battery Usage] INT NULL,
        [Snapp Navigation Refusal__Internet Usage] INT NULL,
        [Snapp Navigation Refusal__Old info] INT NULL,
        [Snapp Navigation Refusal__Not Familiar] INT NULL,
        [Snapp Navigation Refusal__Haven't Used] INT NULL,
        [Snapp Navigation Refusal__Weak timing] INT NULL,
        [Snapp Navigation Refusal__Insufficient Route] INT NULL,
        [Snapp Navigation Refusal__Insufficient UX] INT NULL,
        [Snapp Navigation Refusal__Guide Voice] INT NULL,
        [Snapp Navigation Unsatisfaction__Difficult] INT NULL,
        [Snapp Navigation Unsatisfaction__Distraction] INT NULL,
        [Snapp Navigation Unsatisfaction__Guide Voice] INT NULL,
        [Snapp Navigation Unsatisfaction__Slow navigation] INT NULL,
        [Snapp Navigation Unsatisfaction__Bad Route] INT NULL,
        [Snapp Navigation Unsatisfaction__Weak Estimation] INT NULL,
        [Snapp Navigation Unsatisfaction__Wrong Location] INT NULL,
        [Snapp Navigation Unsatisfaction__Wrong info] INT NULL,
        [Snapp Ride Refusal Reasons__App Problems] INT NULL,
        [Snapp Ride Refusal Reasons__Insufficient Fare] INT NULL,
        [Snapp Ride Refusal Reasons__Short Accept Time] INT NULL,
        [Snapp Ride Refusal Reasons__Not Realized There's Request] INT NULL,
        [Snapp Ride Refusal Reasons__Unfamiliar Route] INT NULL,
        [Snapp Ride Refusal Reasons__Wait for better Offer] INT NULL,
        [Snapp Ride Refusal Reasons__Traffic] INT NULL,
        [Snapp Ride Refusal Reasons__App was Unfamiliar] INT NULL,
        [Snapp Ride Refusal Reasons__Had a Target Destination] INT NULL,
        [Snapp Ride Refusal Reasons__Internet Problems] INT NULL,
        [Snapp Ride Refusal Reasons__Distance to origin was Long] INT NULL,
        [Snapp Ride Refusal Reasons__Long Trip Duration] INT NULL,
        [Snapp Ride Refusal Reasons__Was Working with Tapsi] INT NULL,
        [Tapsi Ride Refusal Reasons__App Problems] INT NULL,
        [Tapsi Ride Refusal Reasons__Insufficient Fare] INT NULL,
        [Tapsi Ride Refusal Reasons__Short Accept Time] INT NULL,
        [Tapsi Ride Refusal Reasons__Not Realized There's Request] INT NULL,
        [Tapsi Ride Refusal Reasons__Unfamiliar Route] INT NULL,
        [Tapsi Ride Refusal Reasons__Wait for better Offer] INT NULL,
        [Tapsi Ride Refusal Reasons__Traffic] INT NULL,
        [Tapsi Ride Refusal Reasons__App was Unfamiliar] INT NULL,
        [Tapsi Ride Refusal Reasons__Had a Target Destination] INT NULL,
        [Tapsi Ride Refusal Reasons__Internet Problems] INT NULL,
        [Tapsi Ride Refusal Reasons__Distance to origin was Long] INT NULL,
        [Tapsi Ride Refusal Reasons__Long Trip Duration] INT NULL,
        [Tapsi Ride Refusal Reasons__Was Working with Tapsi] INT NULL,
        [GPS Glitch Time__Morning(4-9AM)] INT NULL,
        [GPS Glitch Time__Before Noon(9-12PM)] INT NULL,
        [GPS Glitch Time__Afternoon(12-4PM)] INT NULL,
        [GPS Glitch Time__Traffic(4-8PM)] INT NULL,
        [GPS Glitch Time__Night(8-12AM)] INT NULL,
        [GPS Glitch Time__Late Night] INT NULL,
        [GPS Action when Glitch__Switched to Tapsi] INT NULL,
        [GPS Action when Glitch__Decided to stop working] INT NULL,
        [GPS Action when Glitch__Cancelled Trip] INT NULL,
        [GPS Action when Glitch__Changed Location] INT NULL,
        [GPS Action when Glitch__Accepted familiar trips] INT NULL,
        [GPS Action when Glitch__Called Passenger] INT NULL,
        [GPS Action when Glitch__Passenger Help for route] INT NULL,
        [Snapp Usage app__Snapp Box] INT NULL,
        [Snapp Usage app__Snapp Food] INT NULL,
        [Snapp Usage app__Snapp Market] INT NULL,
        [Snapp Usage app__Snapp Trip] INT NULL,
        [Snapp Usage app__Snapp Insurance] INT NULL,
        [Snapp Usage app__Snapp Shop] INT NULL,
        [Snapp Usage app__Internet and Charge] INT NULL,
        [Snapp Usage app__Snapp CarPay] INT NULL,
        [Snapp Usage app__snapp CarFix] INT NULL,
        [SnappDriver App Menu__Snapp Box] INT NULL,
        [SnappDriver App Menu__Snapp Food] INT NULL,
        [SnappDriver App Menu__Snapp Market] INT NULL,
        [SnappDriver App Menu__Snapp Trip] INT NULL,
        [SnappDriver App Menu__Snapp Insurance] INT NULL,
        [SnappDriver App Menu__Snapp Shop] INT NULL,
        [SnappDriver App Menu__Snapp Pay] INT NULL,
        [SnappDriver App Menu__Snapp Investment] INT NULL,
        [SnappDriver App Menu__Internet and Charge] INT NULL,
        [SnappDriver App Menu__Snapp Carpay] INT NULL,
        [SnappDriver App Menu__Snapp Carfix] INT NULL,
        [SnappDriver App Menu__Snapp Cab] INT NULL,
        [Decline Reason__Origin Distance] INT NULL,
        [Decline Reason__Fare] INT NULL,
        [Decline Reason__Route Not Aligned] INT NULL,
        [Decline Reason__Ride Type] INT NULL,
        [Decline Reason__No Incentive] INT NULL,
        [Decline Reason__Trip Length] INT NULL,
        [Decline Reason__Neighborhood] INT NULL,
        [snapp_incentive_category] NVARCHAR(500) NULL,
        [tapsi_incentive_category] NVARCHAR(500) NULL
    );
    PRINT 'Created Cab.DriverSurvey_WideRare';
END
ELSE
    PRINT 'Cab.DriverSurvey_WideRare already exists -- skipped.';
GO

-- ============================================================
-- Cab.DriverSurvey_LongMain  (28 columns)
-- ============================================================
IF OBJECT_ID(N'Cab.DriverSurvey_LongMain', N'U') IS NULL
BEGIN
    CREATE TABLE [Cab].[DriverSurvey_LongMain] (
        [recordID] INT NOT NULL,
        [datetime] DATETIME NULL,
        [_source_file] NVARCHAR(500) NULL,
        [weeknumber] INT NULL,
        [joint_by_signup] INT NULL,
        [active_joint] INT NULL,
        [snapp_ride] FLOAT NULL,
        [tapsi_ride] FLOAT NULL,
        [tapsi_commfree_disc_ride] FLOAT NULL,
        [snapp_commfree_disc_ride] FLOAT NULL,
        [snapp_diff_commfree] FLOAT NULL,
        [tapsi_diff_commfree] FLOAT NULL,
        [snapp_commfree] FLOAT NULL,
        [tapsi_commfree] FLOAT NULL,
        [snapp_incentive] FLOAT NULL,
        [tapsi_incentive] FLOAT NULL,
        [wheel] FLOAT NULL,
        [cooperation_type] NVARCHAR(500) NULL,
        [snapp_LOC] FLOAT NULL,
        [tapsi_LOC] FLOAT NULL,
        [age_group] NVARCHAR(500) NULL,
        [edu] FLOAT NULL,
        [marr_stat] FLOAT NULL,
        [snapp_incentive_category] NVARCHAR(500) NULL,
        [tapsi_incentive_category] NVARCHAR(500) NULL,
        [question] NVARCHAR(500) NULL,
        [answer] NVARCHAR(500) NULL,
        [question_type] NVARCHAR(500) NULL
    );
    PRINT 'Created Cab.DriverSurvey_LongMain';
END
ELSE
    PRINT 'Cab.DriverSurvey_LongMain already exists -- skipped.';
GO

-- ============================================================
-- Cab.DriverSurvey_LongRare  (9 columns)
-- ============================================================
IF OBJECT_ID(N'Cab.DriverSurvey_LongRare', N'U') IS NULL
BEGIN
    CREATE TABLE [Cab].[DriverSurvey_LongRare] (
        [recordID] INT NOT NULL,
        [datetime] DATETIME NULL,
        [_source_file] NVARCHAR(500) NULL,
        [weeknumber] INT NULL,
        [snapp_incentive_category] NVARCHAR(500) NULL,
        [tapsi_incentive_category] NVARCHAR(500) NULL,
        [question] NVARCHAR(500) NULL,
        [answer] NVARCHAR(500) NULL,
        [question_type] NVARCHAR(500) NULL
    );
    PRINT 'Created Cab.DriverSurvey_LongRare';
END
ELSE
    PRINT 'Cab.DriverSurvey_LongRare already exists -- skipped.';
GO
